### ISSUE TITLE
在设置里修改fcitx-remote的路径不起作用

### ISSUE THREAD

**Issue by bincat233** [yuanotes/obsidian-vim-im-switch-plugin#1]
首先谢谢你的插件!!! 真的是字面意义上的 "save my life" !!!

设置页面里修改fcitx-remote的路径为/usr/bin/fcitx5-remote后, 退出设置再进入设置, 发现设置没有改变. 不知道为什么...

所以我临时的解决方案是 `sudo ln -s ./fcitx5-remote /usr/bin/fcitx-remote`

**Comment by yuanotes** [comment]
应该在1.0.3中修复了。
如果还有问题麻烦及时提出。
