### ISSUE TITLE
在我的机器上不能正常工作 - MacBook Air - M1 chip

### ISSUE THREAD

**Issue by johnking** [yuanotes/obsidian-vim-im-switch-plugin#11]
我使用 版本0.14.15

但奇怪的是：
  1. 我可以在操作系统的终端命令行中直接使用 `fcitx-remote -s {im}` 进行输入法的切换， 这里的{im}可以替换成任意的字符串，因为我只有两种输入法：因为和拼音。
  2. 我甚至可以在vim编辑器中，通过调用外部命令的方式执行 fcitx-remote -s anyIM, 也可以正常工作。

我的插件配置如下

<img width="742" alt="截屏2022-06-21 16 13 46" src="https://user-images.githubusercontent.com/1787137/174750940-0b72deab-1801-4a36-b64a-56826b5039b6.png">

**Comment by johnking** [comment]
附图是， 开发者调试窗口的打印信息。

<img width="1005" alt="截屏2022-06-21 16 27 49" src="https://user-images.githubusercontent.com/1787137/174754607-9624a3d3-d10d-44b8-bf09-c0ca0e8ddfce.png">

**Comment by yuanotes** [comment]
可能是因为默认中文导致的，下个版本我改成默认英文。

**Comment by yuanotes** [comment]
1.0.6已经发布了，可以看一下是否还有这个问题出现。如果还出现，请重新打开这个issue。

**Comment by johnking** [comment]
我刚刚更新了，没有解决我的问题， 通过调试窗口的打印信息，发现手工切换输入法之后，插件并没有检测到变化。

<img width="490" alt="截屏2022-06-22 09 03 04" src="https://user-images.githubusercontent.com/1787137/174921614-164cf8e2-ad6c-4901-8006-85f78211bafd.png">


我怀疑，插件调用 /usr/local/bin/fcitx-remote 是否起作用？

是否必须要放到指定目录下，比如 /usr/bin 目录下？

**Comment by yuanotes** [comment]
我看日志，似乎是正常的。这个插件是代替你进行输入法切换的，你不需要手动切换输入法。
如果日志没提示你找不到fcitx-remote，命令就是正常的。

**Comment by johnking** [comment]
可惜，就是不起作用。按道理，切合vim模式之后，打印输出应该有变化，即IM Status 1 -》2， 或者2-》1， 对吧？

另外输入法显示状态栏也应该会从搜狗拼音，切换到美式键盘。但是都没有。

奇怪的是，我直接从终端敲命令， fcitx-remote -s  anysIMString, 都能够修改输入法。

**Comment by johnking** [comment]
方便加个微信？我远程给你示范一下我的桌面？ @yuanotes 

谢谢！

**Comment by yuanotes** [comment]
我重现了，可能是obsidian文件变化引起的。日志出来了，说明有调用命令的。

John King ***@***.***>于2022年6月22日 周三10:53写道：

**Comment by johnking** [comment]
等你的更新！谢谢！

**Comment by johnking** [comment]
我用 im-select 解决了该问题。
