### ISSUE TITLE
等一个windows的支持

### ISSUE THREAD

**Issue by howIsPassword** [yuanotes/obsidian-vim-im-switch-plugin#2]

**Comment by yuanotes** [comment]
嗯，我自己用AHK编译了一个windows fcitx-remote，可以控制windows 拼音的输入法状态。我先自己测试一下，如果没问题的话，我会放到release中。

**Comment by yuanotes** [comment]
先用这个试试 https://github.com/yuanotes/obsidian-vim-im-switch-plugin/releases/download/1.0.3/fcitx-remote.exe
