### ISSUE TITLE
能否win下添加其它输入法或公开ahk的源码

### ISSUE THREAD

**Issue by liang-0131** [yuanotes/obsidian-vim-im-switch-plugin#4]
因为fcitx-remote.exe只能在微软拼音下才有效，在rime小狼毫输入法下无效，所以有此请求

**Comment by AngeloChen14** [comment]
+1 希望加入小狼毫weasel输入法的支持，谢谢！

**Comment by liang-0131** [comment]
> +1 希望加入小狼毫weasel输入法的支持，谢谢！

有ahk源码，其实就在exe右键打开中

**Comment by AngeloChen14** [comment]
> > +1 希望加入小狼毫weasel输入法的支持，谢谢！
> 
> 有ahk源码，其实就在exe右键打开中

谢谢，已经看到了，但还是不知道要怎么修改。请问逆现在找到可以切换小狼毫中英状态的方法了吗？

**Comment by liang-0131** [comment]
> > > +1 希望加入小狼毫weasel输入法的支持，谢谢！
> > 
> > 
> > 有ahk源码，其实就在exe右键打开中
> 
> 谢谢，已经看到了，但还是不知道要怎么修改。请问逆现在找到可以切换小狼毫中英状态的方法了吗？

小狼毫做不到切换中英文只能通过切换输入法的方式

**Comment by yuanotes** [comment]
晚一点我把ahk源码传一下。我只测试了微软输入法，别的输入法还请你们自己测试看看。

**Comment by liang-0131** [comment]
你不是要传源码么

**Comment by yuanotes** [comment]
https://github.com/yuanotes/obsidian-vim-im-switch-plugin/blob/master/fcitx-remote.ahk

liang-0131 ***@***.***> 于2021年12月1日周三 07:28写道：
