### ISSUE TITLE
安装好了fcitx-remote, 但是obsidian切换输入不生效

### ISSUE THREAD

**Issue by sherrier** [yuanotes/obsidian-vim-im-switch-plugin#5]
你好, 我安装好了fcitx-remote, 命令也有返回结果, 但是在obsidian里面编辑,还是没有切换输入法. 
- 插件版本1.0.3 已经打开
- 操作系统是macOS 12.0.1
- obsidian v0.12.19

![image](https://user-images.githubusercontent.com/375406/144697070-cd652bba-8f5e-4d5e-9046-1c9520fe74c8.png)

**Comment by WDayu** [comment]
我也一样不能自动切换输入法，作者写的不是很详细，希望作者能够回应一下，十分感谢。

**Comment by yuanotes** [comment]
看一下 fcitx-remote 的命令是否正确？

获取输入法状态：直接运行 fcitx-remote ，返回 1 是 英文状态，返回2 是中文状态。

改变输入法状态：fcitx-remote -o 激活中文输入法，-c 切换到英文输入法

**Comment by s5unty** [comment]
遇到同样的问题。
原因和 #6 一样，CM6 不支持 `registerCodeMirror` 函数，导致插件不能加载了。

改用「旧版编辑器」解决了我的问题。
![image](https://user-images.githubusercontent.com/50655/150056962-ef2a115c-b0a5-4e8e-b6cc-d460ad56e5eb.png)

有另一个[插件](https://github.com/ALONELUR/vim-im-select-obsidian)，实现的比较简易。

另一些 CM6 相关参考，
https://gitmemory.cn/repo/gavvvr/obsidian-imgur-plugin/issues/20

**Comment by yuanotes** [comment]
等放假我更新一下cm6的支持。

Sun Wuan ***@***.***>于2022年1月19日 周三11:16写道：

**Comment by aik2mlj** [comment]
同样遇到这个情况。感谢作者的付出，希望能尽快更新cm6支持！

**Comment by free-150** [comment]
感谢作者，希望能尽快更新cm6支持！

**Comment by yuanotes** [comment]
…… 这周末吧，最近工作有点忙。其实很好加的，如果你们谁有空发个pr就好了。

free-150 ***@***.***> 于2022年2月24日周四 15:40写道：

**Comment by circleapps** [comment]
我在Windows 10上也遇到了这个问题，测试了一下 fcitx-remote.exe，没有打印出任何返回值。

**Comment by circleapps** [comment]
我查了一下 AHT 的 文档，可以在脚本最前面加上 
;@Ahk2Exe-ConsoleApp
来保证stdout能打印输出。

![image](https://user-images.githubusercontent.com/44904628/157760258-2f202209-302d-4840-825f-9afc0be04cdd.png)


我编译了一下，确实管用。

**Comment by yuanotes** [comment]
1.0.4已支持CM6

**Comment by Vertin0302** [comment]
最近obsidian更新了个版本好像就用不了？
