### ISSUE TITLE
可以在启动或打开文件时判断吗

### ISSUE THREAD

**Issue by Azureki** [yuanotes/obsidian-vim-im-switch-plugin#7]
感谢作者开发插件，现在 obsidian 的 vim 模式好用多了。
我用了一段时间发现启动时并不会切换状态。当然，这也没有错，因为最开始就是Normal，不算是“切换到”Normal。
是否有办法在最开始（启动obsidian，或创建新文件）也判断一次呢？

**Comment by yuanotes** [comment]
不太明白你的意思，是说一开始如果输入法是中文状态，就切换到英文状态吗？

**Comment by yuanotes** [comment]
1.0.6已经发布，请升级看一下，是否问题已解决。
